print("-Ingresa tus datos-\n")
nombre=(input("Ingresa tu nombre:\n"))
num_tel=int(input("Ingresa tu n'umero de tel'efono:\n"))
direc=(input("Ingresa tu direcci'on:\n"))
edad=int(input("Ingresa tu edad:\n"))
nacio=(input("Ingresa tu nacionalidad:\n"))
fechnam=(input("Ingresa tu fecha de nacimiento:\n"))
alt=float(input("Ingresa tu altura:\n"))
peso=float(input("ingresa tu peso:\n"))

print("-Ficha de datos-\n")
print("Nombre: ",nombre)
print("N'umero de tel'efono: ",num_tel)
print("Direcci´on: ",direc)
print("Edad: ",edad)
print("Fecha de nacimiento: ",fechnam)
print("Altura: ",alt)
print("Peso: ",peso)
print(type(nombre))
print(type(num_tel))
print(type(direc))
print(type(edad))
print(type(fechnam))
print(type(alt))
print(type(peso))